### ISSUE TITLE
GitHub OAuth login

### ISSUE THREAD

**Issue by yegor256** [artipie/central#1]
Let's make it possible to login/logout via GitHub OAuth. This will give us an ability to show users their repository YAML configs and let users edit them.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) I'm not managing this repo, remove the [webhook](https://github.com/artipie/central/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/central` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by artemlazarev** [comment]
Lets make that feature after we will implement automatic deploy (CI|CD)of new releases.

**Comment by g4s8** [comment]
Done in https://github.com/artipie/central/commit/2a0d63f388dab0f8ed6d5e8bc069ebcdd29c057f

**Comment by 0crat** [comment]
I'm not managing `artipie/central` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
