### ISSUE TITLE
Redirect to www.artipie.com

### ISSUE THREAD

**Issue by g4s8** [artipie/central#5]
Redirect main page to www.artipie.com instead of `/central`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I'm not managing this repo, remove the [webhook](https://github.com/artipie/central/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/central` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
Done in https://github.com/artipie/central/commit/9519d45b57ebbaf4792d6d8caa00abb50ad1efa1

**Comment by 0crat** [comment]
I'm not managing `artipie/central` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
