### ISSUE TITLE
Access denied to public artipie central

### ISSUE THREAD

**Issue by pavlukhin** [artipie/central#6]
I did following:
1. Opened https://www.artipie.com/
2. Followed a link https://github.com/login/oauth/authorize?client_id=0f33052d9fee8303c36e&redirect_uri=https://central.artipie.com/auth and granted requested application access on GitHub.
3. Followed a next suggested link https://central.artipie.com/pavlukhin and observed "Access to central.artipie.com was denied" (HTTP ERROR 403).

Am I doing something wrong?

**Comment by 0crat** [comment]
@pavlukhin[/z](https://www.0crat.com/u/pavlukhin) I'm not managing this repo, remove the [webhook](https://github.com/artipie/central/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/central` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@pavlukhin sorry for the delay. Right now only invited users can login to central, I've granted permissions to `pavlukhin` GitHub user, please try to login again.

**Comment by pavlukhin** [comment]
@g4s8 thank you. Now it works for me. Actually it is misleading that a friendly invitation in https://www.artipie.com/ does not actually allow to host anything without an additional permission request. It might be useful to state it explicitly (may be in a response body with 403 code).

Also I had to figure out that some more steps are needed to upload/download artifacts:
1. Set a password for my user.
2. Define explicit permissions (in repository config yaml) for my user, wildcard ones did not work for me.

My impression is that user experience is not so smooth.

**Comment by pavlukhin** [comment]
Not sure what to do with this issue. On one hand it can be closed as I got needed access. On the other hand some improvements could be done, possibly in other tickets. @g4s8 what do you think?

**Comment by g4s8** [comment]
@paulodamaso I'm working on these tickets right now:
 - https://github.com/artipie/artipie/issues/285
 - https://github.com/artipie/artipie/issues/287

Maybe it'll improve the usability.
Definitely we need to point about invitation process on the main page.
