### ISSUE TITLE
Why this repository contains go code?

### ISSUE THREAD

**Issue by Sammers21** [artipie/central#9]
Please explain why does this repository contains go code, considering the fact that artipie and modules around are in java.

I'm creating this issue because in #8 @g4s8 was not able to respond to my question.

**Comment by g4s8** [comment]
@Sammers21 I've explained it in readme file: https://github.com/artipie/central/tree/master/login

It's simple sidecar project only for central.artipie.com, it's not supposed to be maintained actively, and there are no work in the scope to be done.

**Comment by Sammers21** [comment]
@g4s8, thanks for the response.
